Somehow-I-Code/marquei

src/app/page.tsx

We mistakenly removed the CompanyLogo component from the home page while solving a merge conflict. That commit revert that change back to the expected value.

add again company logo component to the home page

---

web/src/app/components/bottom-floating-menu.tsx
web/src/components/ui/button.tsx

As it was
It is now
A bug was found when you click on buttons on flooting menu.

add style element in hover on flooting menu

---

api/package-lock.json
api/package.json

O pacote do zod não se encontra nas dependências do projeto.
Um dos motivos pra que o projeto esteja funcionando mesmo sem ele estar corretamente instalado é pelo fato dele estar presente no nosso node_modules daquele aula de discussão de backend que a gente teve.
Se a pasta for removida, o projeto para de funcionar.
Precisamos refazer a instalação do pacote.

Install zod in the api project

---

web/src/app/login/components/login-form.tsx
web/src/app/login/page.tsx

Esse PR trata as respostas de sucesso e fracasso do login.
Caso o status da resposta seja 200 (Sucesso) será gerado um token para autenticar o usuário, o token é salvo no navegador e o usuário e redirecionado para a tela home.
Se o o status da resposta for diferente de 200, será lançado um toast na tela apresentando um erro para o usuário. 
Toast com a mensagem de erro:

Tratar as respostas de sucesso e fracasso no login

---

api/prisma/migrations/20240529010100_create_company_model/migration.sql
api/prisma/schema.prisma

Nosso projeto ficará alocado em um servidor nas nuvens, para que o cliente possa acessar via web, e como poderemos ter clientes com diferentes tipos de serviço de agendamento, o conceito company irá separa cada cliente dentro do nosso aplicativo. Basicamente, existirá apenas um aplicativo Marquei no servidor nas nuvens, e cada company será um cliente, então teremos várias companys (clientes) dentro de um aplicativo só, sendo cada company (clientes) identificados pelos campos criados nesse model do PR. Eu fiz no excalidraw o esquema do conceito company, espero que essa imagem ajude no entendimento.
1.  Dentro do arquivo schema.prisma, foi criado o model Company;
2.  O model Company contém os campos que foram informados na descrição da tarefa SCRUM-117 no jira (link da terefa: …

A model company was created, and run prisma migrate

---

api/.env.example
api/src/repositories/profiles.ts
api/src/services/email.ts

Quando um novo usuário é criado, a senha é mostrada apenas no terminal do vscode. Se o terminal for atualizado, a gente acaba perdendo acesso a essa senha e precisamos de um novo usuário pois é impossível logar sem a senha.
Esse pull request adiciona a habilidade de enviar as senhas no slack, assim temos acesso ao usuário com a senha bastando procurar no canal correspondente no slack.
Eu faço uma requisição para um endpoint do slack de um app criado por mim com o fim de automatizar mensagens do slack.
Esse endpoint roda apenas um `fetch` normal com algumas informações necessárias pro hook. Quando esse endpoint é chamado, o slack automaticamente manda uma mensagem pra mim no slack com o texto que eu forneci.
Eu mantive a mensagem no terminal como um fallback pra caso o slack tenha algum …

SCRUM-127 envia senhas auto geradas no slack

---

api/Dockerfile
api/prisma/migrations/20240601221734_update_update_at_field_in_profile/migration.sql
api/prisma/schema.prisma

Toda vez que a gente criava uma migration, essa migration era criada com sudo e depois o git não conseguia remover. Fazendo com que a gente tivesse que rodar comandos extras pra poder deletar essa migration quando trocávamos de branch.
Como bônus e teste, esse PR vai atualizar o campo `updatedAt` do modelo `Profile` por conta de um erro do digitação.
Quanto à alteração do model é apenas uma correção de nome simples. Sem segredos.
Quanto à reconfiguração do `Dockerfile`, passos extras são feitos pra garantir que a pasta `prisma` de dentro do `node_modules` não tenha permissões sudo. Dessa maneira, a gente não vai incorrer no fato de que a permissão pra criar arquivos com esse comando pode ser alta demais.
- `make run` deve ser capaz de resolver todas as atualizações depois da atualização …

SCRUM-123-update-field-in-profile-model

---

api/src/http/routes/login.ts
api/src/http/routes/reset-password.ts
api/src/validators/login-form.ts
api/src/validators/reset-password.ts

Esse PR cria o token de reset de senha, esse token será único para cada usuário que solicitar o reset e irá servir como um link para que o usuário acesse a tela onde será criada a nova senha. 
O link será: `http://localhost:3001/password-reset/[token]`
No lugar de `[token]` será o token gerado.
Foi adicionado um `if` que verifica se a `JWT_SECRET` está definida no arquivo `.env`, se a `JWT_SECRET` não estiver definida será retornado um erro de status (500) com a mensagem "JWT SECRET não configurado".
Se a a `JWT_SECRET` estiver configurada corretamente será gerado um token usando o id e e-mail do usuário. O token também terá um campo `expiresAt` que define em quanto tempo o token gerado irá expirar, para esse caso cada token irá expirar em 1 hora.
- Rodar a aplicação
- Mandar uma …

Create reset password token

---

api/src/http/routes/change-password.ts
web/src/app/change-password/components/change-password-form.tsx
web/src/app/change-password/page.tsx

Inicialmente, é necessário que o usuário esteja autenticado para poder criar uma nova senha. Ao usar esta funcionalidade, o usuário deve inserir sua senha antiga e, em seguida, criar uma nova senha e confirmá-la. Depois, as informações serão enviadas para o banco de dados para verificação e atualização da senha. Assim, uma mensagem de sucesso ou de erro será retornada.
- O token de autenticação é colado manualmente para permitir a alteração da senha e é íncluído o "authorization" no cabeçalho da requisição.
- Usa o fetch para enviar as informações para banco de dados (O endpoint change-password).
- O componente toast é usado para mostrar uma mensagem de sucesso e redirecionar o usuário para página de perfil. O mesmo componente é utilizado para retornar mesangens de erro.
- No terminal …

Fazendo onsubmit e envio de DB.

---

web/package-lock.json
web/package.json
web/src/app/new-company/components/new-company-form.tsx
web/src/app/new-company/page.tsx
web/src/app/new-profile/components/new-profile-form.tsx
web/src/app/new-resource/components/newResourceForm.tsx
web/src/components/ui/switch.tsx

Mostra a tela com o formulário que permitirá o cadastro de uma empresa, através da rota `http://localhost:3001/new-company`.
Este PR contém, apenas, o layout da tela cadastrar empresa. Não contém a lógica, ou seja, não faz o envio do form, e os botões não funcionam, esta parte será implementada em um outro PR. Estou fazendo esta separação para que a revisão fique mais fácil e rápida.
Utilizei como referência o layout "Criar uma empresa" desenhado no figma.
Na web foi criado a rota `new-company`. Esta rota contém o componente `new-company-form` no qual tem o formulário solicitando os dados necessários para criar uma empresa.
O componente `new-company-form` é chamado dentro de page. tsx, no qual contém o restante do layout da página (logo do projeto e título da tela).
Apenas relembrando, …

Criando o layout da tela de cadastrar empresa

---

api/index.ts
api/requests/company/create-company.http
api/src/http/routes/create-categories.ts
api/src/http/routes/create-company.ts
api/src/repositories/categories.ts
api/src/repositories/company.ts
api/src/repositories/resources.ts
api/src/validators/categories.ts
api/src/validators/company.ts
api/src/validators/resources.ts

Para cadastrar uma empresa via aplicativo, é necessário registrar os dados do form no DB, sendo assim, neste PR foi criado a rota  `company` para salvar os dados da requisição no DB.
Foi feito melhorias em alguns repositories e validators, então, qualquer arquivo que não envolva a  rota de criação de company será considerado como melhorias, ressaltando que essa parte não é o foco desta tarefa, apenas vi que tinha que ser melhorado e aproveitei esse PR para fazer.
Foi necessário criar e registrar a rota `company`, solicitando as informações da requisição, e obtendo como retorno os dados salvos no DB. Dentro dessa rota os dados do form são enviados pro repository que ficará encarregado de inserir as informações no DB. E também, essas informações passam pelo validator `company` no qual …

Criando rota de new company

---

api/prisma/migrations/20240816193055_add_city_nickname_representative_name_to_company/migration.sql
api/prisma/schema.prisma
api/src/http/routes/create-company.ts
api/src/repositories/company.ts
api/src/validators/company.ts
api/src/validators/profile.ts
web/src/app/new-company/components/new-company-form.tsx
web/src/app/new-profile/components/new-profile-form.tsx

Nossa plataforma permite cadastrar empresas com nomes iguais, e a falta de distinção pode acabar confundindo o usuário de usar a empresa correta pro seu cadastro. Sendo assim, este PR adiciona os campos `city`, `nickname` e `representativeName` no momento de criar uma empresa, com o objetivo de diferenciar as empresas que foram cadastradas com o mesmo nome.
Foi adicionado os inputs, `city`, `nickname` e `representativeName`, na tela `new-company`. Esses novos dados enviados pela requisição, passam por uma validação e as informações são armazenados no DB, retornando como resposta um cadastro realizado com sucesso.
1. Acessar a página: `http://localhost:3001/new-company`;
2. Realizar múltiplos cadastros de empresas, preenchendo os campos da tela. Fazer cadastros de empresas com nomes …

Adicionando campos que identificam as empresas que foram cadastradas com nomes iguais

---

api/prisma/migrations/20240827220347_add_name_category/migration.sql
api/prisma/schema.prisma
api/requests/categories/create-category.http
api/src/http/routes/create-categories.ts
api/src/repositories/categories.ts
api/src/validators/categories.ts
web/src/app/new-category/page.tsx
web/src/app/new-resource/components/new-resource-form.tsx
web/src/app/page.tsx
web/src/types/categories.ts
web/src/types/resources.ts

#MUDANÇA DA VARIÁVEL 'TITLE' PARA 'NAME'
Havia vários nomes de variáveis referente a tabela Categoria, onde alguns arquivos utilizam **'title'** e outro **'name'**. Para padronizar, este pull request modifica todas variáveis de **'title'** para **'name'** em todos arquivos relacionado à Categoria.
Para mudar o **'title'** para **'name'**, primeiramente atualizei o schema do Prisma e o banco de dados na tabela _'Category'_. Em seguida, modifiquei os arquivos relacionados à tabela. Por exemplo, no API, o arquivo create-categories.ts foi atualizado, assim como os demais arquivos relacionados.
- No terminal, digite: **`make run`**.
- Para atualizar o schema prisma no local. No terminal, digite: **`cd api`** > **`npm i`** > **`npx prisma generate`** > **`make api`** > **`npx prisma generate`** …

Alterado todos variáveis de 'title' para 'name'

---

api/requests/resources/create-resource.http
api/src/http/routes/create-categories.ts
api/src/http/routes/create-resources.ts
api/src/http/routes/get-categories.ts
api/src/http/routes/get-resources.ts
api/src/repositories/categories.ts
api/src/repositories/resources.ts

As rotas de categorias e recursos estavam incompletas, pois não incluíam a parte de autenticação e verificação no banco de dados. Para resolver esse problema, foi adicionado o token de autenticação e verificação em cada arquivo relacionado a categorias, recursos e mensagem de erro de operação não permitido para o usuário não cadastrado, por exemplo, tentar criar uma categoria de outra companhia que isso não é permitido. Além disso, o Id da companhia, agora é obrigatório, foi incluído para garantir o acesso e .
O ajuste nas rotas de categorias e recursos foi realizado acrescentando o token e a verificação nos arquivos `create-categories.ts`, `get-categories.ts`, `create-resources.ts` e `get-resources.ts`, a rota de create foi colocado uma mensagem de erro não permitindo o SUDO/ADMIN/USER …

Scrum 162 atualizar rotas de resource e category para usar token

---

api/index.ts
api/requests/profiles/profiles-list.http
api/src/http/routes/profiles-list.ts
api/src/repositories/profiles.ts

Cria o endpoint que busca o perfis de cada company.
1. Verificação de permissões (isSudo):
- Se o usuário for SUDO (isSudo for true), ele tem permissões elevadas e, por isso, o código não aplica restrições adicionais. O sistema busca todos os perfis da empresa correspondente ao companyId, independentemente do nível de permissão de cada perfil.
- Se o usuário não for SUDO (isSudo for false), o código aplica uma restrição para que ele não possa visualizar perfis de outros usuários SUDO. Isso é feito através da cláusula level: { not: 'SUDO' }, que filtra a busca e retorna apenas os perfis que não têm o nível 'SUDO'.
2. Estrutura condicional:
- A função está estruturada para diferenciar claramente o que deve ser retornado dependendo do nível de permissão do usuário.
- Usuário SUDO: Pode ver …

Create profiles list endpoint

---

api/index.ts
api/requests/company/get-companies.http
api/src/http/routes/get-companies.ts
api/src/repositories/company.ts
web/src/app/new-profile/components/new-profile-form.tsx
web/src/app/new-profile/page.tsx
web/src/types/companies.ts
web/src/types/profiles.ts

A tela de **"Novo Perfil"** estava apresentando um erro 500 (Internal Server Error). Inicialmente, foi necessário identificar o problema para exibir corretamente a tela de **"Novo Perfil"**. Durante os testes, novos erros apareceram ao salvar, especialmente relacionados ao campo companyId, que é obrigatório. No frontend, foi adicionada uma caixa de seleção que mostra uma lista de empresas (Fica visível somente SUDO) ou uma empresa (Visível somente ADMIN). Usuários com nível USER verá uma tela 404 (Sem permissão para criar um novo perfil).
Para fazer a tela de **"Novo Perfil"** funcionar corretamente foram:
- No frontend, foi inserido um token na função getLevels para que a seleção de nível exiba as opções de perfil de acordo com o nível do usuário logado.
- Para corrigir o erro …

Erros corrigidos - Tela Novo Perfil

---

api/index.ts
api/requests/reset-password/reset-password.http
api/src/http/routes/create-new-password.ts
api/src/http/routes/reset-password.ts
api/src/validators/create-new-password.ts
web/src/app/reset-password/[token]/components/create-new-password-form.tsx
web/src/app/reset-password/[token]/page.tsx
web/src/app/reset-password/components/send-email-form.tsx
web/src/app/reset-password/page.tsx

Esse PR conecta o front-end e back-end da tela reset password e permite que seja possível realizar o fluxo completo de reset de senha pelo front-end.
Quando o usuário pede para redefinir a senha, o back-end gera um token temporário e envia para o slack. Esse token prova que o pedido é válido e foi autorizado. O token gerado se torna um complemento da url http://localhost:3001/reset-password e através dessa url o usuário acessa a tela onde é possível criar a nova senha.
No momento da redefinição, o código verifica se a nova senha e a confirmação estão corretas e correspondem entre si. Em seguida, a nova senha é criptografada e salva no banco de dados.
Após isso o usuário e redirecionado automaticamente para a tela de login onde ele pode acessar a aplicação com sua nova senha.
- Acessar …

Connecting front-end and back-end of reset-password screen

---

web/src/app/new-category/component/new-category-form.tsx
web/src/app/new-category/page.tsx
web/src/types/categories.ts

Ao fazer teste da tela apresentou erro de companyId que é obrigatório. Para resolver o problema, foram adicionados o companyId nos arquivos. Também foi incluída a lógica para decodificar o session e obter o companyId do usuário logado para fazer a criação de nova categoria.
Os passos para a resolução do problema foram:
- Foi identificado um erro relacionado ao companyId, então ele foi adicionado ao arquivo `new-category-form.tsx` no **FormSchema**, na **Props** e no **FormField**. Da mesma forma, foi incluído na pasta **types**.
- No campo FormField do **companyId**, foi definido a tag Input do type="hidden", para que o usuário não veja na tela, mas ainda será enviado nos dados.
- Antes de enviar para o banco de dados, o **companyId** passa por uma conversão de **string** para o …

Solved error on new category screen

---

web/src/app/new-resource/page.tsx
web/src/types/resources.ts

Este pull request resolve erros relacionados ao categories.map e a falta de companyId (“Empresa é obrigatório, contate o suporte”). A solução foi adicionar o token na função getCategories para que a tela fosse exibida corretamente. Portanto, foi feita uma decodificação na sessão para obter o companyId do usuário para criar um novo recurso.
- Adicionado o token na função **getCategories**. Com a mudança, a tela voltou a ser exibida corretamente;
- Decodifica a sessão para obter o companyId do usuário logado e permitindo que esse valor seja enviado ao banco de dados.
- No terminal, execute o comando `“make run”`
- Abre o navegador e acesse [localhost:3001/new-resources](url) para testar a criação de um novo recurso.
Print de teste:
SUDO:
ADMIN:
USER:

Solved error on new resource screen

---

web/src/app/components/resources-card.tsx

Este pull request foi criado para melhorar o estilo de descrição mostrada abaixo do recurso. Antes, em cada descrição apresentava as frases sem fim, ultrapassando 4 linhas. Agora, foi definido de ter 2 linhas para a descrição. 
A solução foi utilizando Tailwind CSS. Adicionei a classe line-clamp-* ( * indica o número de linhas desejado) no componente resource-card, especificamente no estilo da descrição (Onde tem o campo description).
- Abre o navegador e acesso [localhost:3001/](url) e verifique a mudança do estilo da descrição dos recursos mostra as 2 linhas.
Prints testes:
Antes:
Depois:

2 lines of description (style)

---

api/src/http/routes/create-company.ts
web/src/app/new-company/page.tsx

Antes a tela era exibida para todos os níveis de usuários. Agora, foi ajustado para que usuário com nível SUDO possam visualiza-lá. Caso ADMIN ou USER tente acessar a página, responderá a página 404 (Not found). Além disso, foram implementadas autenticação e segurança no backend, que anteriormente estavam ausentes ao criar uma nova empresa.
- Usa decodificação da sessão para ver o nível de usuário para obter permissão de visualizar a tela (Somente SUDO). Usuários com nível ADMIN ou USER são redirecionados para a página 404 (Not Found).
- Adiciona o token e a chave secreta na rota `create-company.ts`, garantindo que apenas usuários SUDO possam criar uma nova empresa.
- Faça atualização da sua main local no terminal: `npm i`
Print de teste:
SUDO criou uma nova empresa que é o Id 12: …

ADMIN/USER don't see screen "Create Company"

---

web/src/app/components/empty-resources-list.tsx
web/src/app/page.tsx

Corrige o problema onde a mensagem de "nenhum recurso disponível" aparecia mesmo quando já havia recursos cadastrados.
Foi adicionado um if que verifica se existem recursos antes de exibir a mensagem de "sem recursos". Se não houver nenhum recurso, a mensagem é mostrada. Caso contrário, ele exibe os recursos organizados por categorias.
Basta acessar a aplicação com um perfil que não tem nenhum recurso cadastrado e depois acessar com um perfil que já tem recursos cadastrados.
Perfil sem recursos:
Perfil com recursos:

Fix resource list display logic for empty state

---

README.md
scripts/marquei.sh
setup.sh

Scripts make são legais e tal mas eles demandam que você esteja sempre na raiz do projeto, o que pode ser um saco. Além disso, sua estrutura de pontos `make containers.start` faz com que a digitação seja menos natural.
Com um único comando a partir da raiz da aplicação:
```bash
$ zsh setup.sh
```
Uma sequência de scripts será adicionada ao seu terminal te dando super poderes.
Desses, vale a pena destacar os seguintes:
- `marquei` mostra todos os comandos disponíveis
- `marquei run`, `marquei run detached` e `marquei stop` podem ser rodados de qualquer pasta da aplicação
- `marquei install` instala todas as dependências locais dos projetos `web` e `api` além de gerar todos os modelos do prisma novamente. Ideal pra quando você dá aquele pullzinho maroto na main.
Você pode testar essa …

Adiciona 2 scripts pra melhorar o uso e manutenção da aplicação

---

api/src/http/middlewares/admin-route.ts
api/src/http/middlewares/find-logged-user.ts
api/src/http/middlewares/refresh-token.ts
api/src/http/middlewares/sudo-route.ts
api/src/http/middlewares/validator/requests.ts
api/src/http/routes/get-categories.ts

A gente teve um problema com uso de valores adicionados ao middleware por conta da impossibilidade de informar sempre que as requests podiam possuir determinados valores.
Por cant disso, nosso código estava cheio de ifs desnecessários, pois o middleware garantiria que o código só atingiria aquele bloco caso desse tudo certo nas checagens antecedentes. Porém como tudo era feito em arquivos separados, o typescript não tinha condição de garantir essas checagens.
Esse PR faz uso do zod para simplificar a extração de valores da request. Fazendo um parse da request dentro de um schema, é possível extrair os valores já tipados. Caso alguma extração falhe, a api responderá com um 500.
Faça uma requisição ao get-categories e vc deve ver um agrupamento de dados junto de um token atualizado.

Melhoria no uso de valores adicionados via middleware à request

---

web/src/app/resource/list/components/categories-list.tsx

A lista de categorias não estava se comportando como esperado.
Adiciona um observer de interseção na tela que fica vigiando quando uma nova seção entra na tela.
- Acesse a tela de lista de recursos, navegue usando as categorias.

Adiciona content aware scrolling to categories pills

---

api/package-lock.json
api/package.json
api/src/http/controllers/appointment.ts
api/src/http/routes/appointments/index.ts
api/src/repositories/appointments.ts
api/src/services/appointments.ts
api/src/validators/appointments.ts

BUSCAR TODOS OS AGENDAMENTOS BASEADO EM UM DIA
Foi criado uma requisição para buscar todos os agendamentos de um determinado dia, sem utilização de filtro.
Primeiramente, utilizei a biblioteca `date-fns`, que torna o código mais semântico, limpo e com menor risco de erros.
No repositório, foi adicionada a função `findByDay`, responsável por buscar os agendamentos de um determinado dia.
Essa busca é feita através do Prisma, utilizando o campo `startsAt`, conforme definido na tabela appointment.
Além disso, foram implementados os ajustes necessários nas partes de services, controllers, validators e routes, para que a requisição de busca funcione corretamente.
- Atualize a branch `main` e execute `npm i` na API para instalar as dependências do `date-fns` localmente.
- Para realizar um teste, …

Buscar todos os agendamentos 

---

api/src/http/controllers/appointment.ts
api/src/http/routes/appointments/index.ts
api/src/repositories/appointments.ts
api/src/services/appointments.ts
api/src/validators/appointments.ts

Adiciona a funcionalidade de criação de agendamentos via rota POST /appointments.
Implementa uma rota `POST `que valida os dados com Zod e salva no banco com o Prisma. A lógica foi separada em controller, service e repository. Também foram adicionados tratamentos de erro para garantir respostas claras em caso de falhas.
- Rodar a aplicação com `marquei run`
- Acessar o postman ou alguma ferramenta similar e enviar uma requisição POST para `http://localhost:8080/appointments` com um corpo JSON como este:
- Verificar se a resposta retorna status 201 e se o registro foi salvo corretamente usando o prisma studio.

Create route POST to create appointments
