src/app/page.tsx, src/app/styles.css
Inserção de um botão e alteração da cor de fundo para azul.
=> Inserção de um botão e alteração da cor de fundo para azul.

src/app/page.tsx, src/app/style.css
=> SCRUM-7-navigation-bar

src/app/components/CategoriesList.tsx, src/app/components/Pill.tsx
=> Scrum 10 criar o componente de pilula

api/index.ts
in this commit creates resources endpoint that will be used in the future to retrieve all relevant data from each user's resources
=> create resources endpoint

api/docker-compose.yml
Pra fazer esse pull request funcionar, vcs devem fazer a instalação do docker.
Deve ser uma instalação bem padrão, mas vcs podem ver mais informações aqui: https://docs.docker.com/desktop/wsl/
O link direto pra download do docker pode ser encontrado aqui: https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe?_gl=1*1h582ix*_ga*MzA2MjMxNDczLjE3MDkxNjg0NjA.*_ga_XJWPQMJYHQ*MTcwOTE2ODQ1OS4xLjEuMTcwOTE2ODQ2MC41OS4wLjA.
Agora, toda vez que vcs reiniciarem suas máquinas, precisam garantir que o docker esteja em execução.
Feito isso, vcs podem startar o container com os seguintes passos:
```bash
cd api
docker compose up -d
docker ps
```
=> Scrum 36 add docker for postgres

web/package-lock.json, web/package.json, web/src/app/components/bottom-floating-menu.tsx, web/src/app/components/sheet-menu.tsx, web/src/components/ui/sheet.tsx
=> Add sheet placeholder to menu

api/src/http/routes/create-category.ts, api/src/http/routes/create-resources.ts
Segue link das anotações no Notion
https://www.notion.so/Somehow-I-code-636e572587594ed0a75663bd0e4c3fdf
=> Exclusão das linhas comentadas

web/src/app/account/page.tsx
Ao clicar no botão voltar para home o link redireciona para a tela home.
=> Create account screen placeholder

web/src/app/login/page.tsx
Ao clicar no botão de login o link redireciona para a tela home.
=> Create login screen placeholder

web/src/app/add-categorie/page.tsx, web/src/app/new-category/page.tsx
Ao clicar no botão voltar para home o link redireciona para a tela home.
=> Create add category screen placeholder

web/src/app/resource-details/page.tsx
Ao clicar na logo ou no botão "Voltar para home" os links direcionam para a tela home.
=> Create screen to view resource details

web/src/app/resource-details/page.tsx
O intuito desse PR é corrigir provisoriamente o erro que está acontecendo na tela resource-details
=> Adicionar o atributo resources com objeto vazio 

web/package-lock.json, web/package.json, web/src/app/components/form-title.tsx, web/src/app/new-resource/page.tsx, web/src/components/ui/button.tsx, web/src/components/ui/input.tsx, web/src/components/ui/label.tsx, web/src/components/ui/select.tsx, web/src/components/ui/textarea.tsx
Com o objetivo de deixar o PR menor e mais fácil de ser revisado, este contém apenas o layout da página novo recurso. Os botões e o form não estão funcionando, irei implementar a lógica de cada um deles numa outra tarefa.
Criei um componente chamado "FormTitle" no qual todos poderão usar na sua página. Esse componente se refere ao nome do form, no caso da minha tela se chama "Novo recurso", mas em outras tem o nome de "Nova categoria", "Recuperar senha", "Alterar senha", "Criar perfil"...
Esse componente estabelece a mesma estilização (tamanho e cor da fonte...) para o título do form, assim não cometeremos o erro de deixar as páginas fora do padrão.
=> create the new resource page and the form title component

web/package-lock.json, web/package.json, web/src/app/new-category/component/new-category-form.tsx, web/src/app/new-category/page.tsx, web/src/components/ui/form.tsx
Como a Gisele disse fazer PR para ficar mais fácil, então eu fiz a tela de Nova Categoria usando shadcn/ui e seguindo o layout do figma.  
Agora a tela de nova categoria em espaçamento aproximada da tela de novo recurso:
=> Tela new category

web/package-lock.json, web/src/app/layout.tsx, web/src/app/new-resource/components/newResourceForm.tsx, web/src/app/new-resource/page.tsx, web/src/app/page.tsx, web/src/components/ui/toast.tsx, web/src/components/ui/toaster.tsx, web/src/components/ui/use-toast.ts
Neste PR as informações inseridas no form foram salvas no banco de dados.
Imagem de como fica a tela home quando se tem recursos cadastrados.
Imagem do prisma studio mostrando que as informações estão salvas no banco de dados via tela novo recurso.
=> SCRUM-96-salvar as informacoes do novo recurso no banco de dados via form

web/src/app/new-category/component/new-category-form.tsx, web/src/app/new-category/page.tsx
Colocando toast no new-category-form e error
=> Colocando action toast do form new-category-form

web/src/app/new-account/components/newAccountForm.tsx, web/src/app/new-account/page.tsx
Este PR trata apenas do layout da tela novo perfil. A lógica da página será tratado em outros PRs. Segue imagem de como ficou a tela.
=> Scrum 80 implementar UI da tela criar conta

api/package-lock.json, api/package.json, api/src/http/routes/login.ts
Nesse PR instalei a biblioteca bcrypt para fazer a comparação da senha enviada na requisição de login com a senha no banco de dados.
=> Check login request password

api/index.ts, api/src/http/routes/get-levels.ts, web/src/app/new-account/components/newAccountForm.tsx, web/src/app/new-account/page.tsx, web/src/components/ui/select.tsx
Neste PR adicionei o nível de perfil no backend e no NewAccountForm.
Segue imagem de como ficou o campo.
=> Add profile level from backend on select in NewAccountForm

api/package-lock.json, api/package.json, api/src/http/routes/login.ts
Esse PR cria o token jwt para autenticar os usuários caso as credenciais tenham sido validadas.
=> Create the jwt with email and profile level data

web/src/app/change-password/components/change-password-form.tsx, web/src/app/change-password/page.tsx
Este PR é somente tela de alterar senha, para ver como ficou de acordo com figma. Depois vou abrir outro PR para colocar ação da tag eye/eyeoff.
=> Tela de alterar senha sem ação de eye

web/src/app/new-profile/components/new-profile-form.tsx, web/src/app/new-profile/page.tsx
Neste PR o form está fazendo o envio dos dados, e os mesmos estão sendo salvos no DB. A partir do merger desta PR, o perfil poderá ser criado diretamente pelo aplicativo.
Segue a tela com o toast
=> Scrum 100 fazer o envio do form e adicionar o toast

web/src/app/change-password/components/change-password-form.tsx
Parte ao entrar na página de "Alterar a senha":
Esta tela abaixo ao clicar o botão eye, muda para eyeOff.
=> Adicionando ação de eye/eyeOff

api/src/repositories/profiles.ts, api/src/services/email.ts
**Neste PR fiz as seguintes implementações:**
- Criei uma pasta dentro de api/src chamado services, e dentro dela criei o arquivo email.ts;
- Esse arquivo tem a classe EmailService, no qual contém uma função de serviço de e-mail; 
- A função sendEmailWithPassword exibe um console.log com a senha gerada pelo generatePassword();
- O generatePassword() só é executado quando se cria um novo perfil;
- A função sendEmailWithPassword é chamada dentro da função assíncrona create, da classe ProfileRepository;
- É possível visualizar o console.log no terminal do VS code.
**Resumo:**
O console.log deste PR simula um disparo que faremos para o e-mail do novo perfil criado. No e-mail terá a senha gerada pelo sistema, pro usuário fazer o seu primeiro acesso, e posteriormente alterar a senha. Ou seja, …
=> Email service criado

api/index.ts, api/requests/reset-password/reset-password.http, api/src/http/routes/reset-password.ts, api/src/validators/reset-password.ts
Este pull request implementa um endpoint para resetar a senha dos usuários. 
O código implementa o endpoint `/reset-password` que aceita requisições POST. Quando um usuário faz uma solicitação para resetar a senha, o endpoint valida o email fornecido no request.body e verifica se ele existe no banco de dados. Se o email não for encontrado, uma resposta 404 é retornada com a mensagem "Email não encontrado".
1. Iniciar o servidor: Rodar a aplicação com  `make run`
2. Configurar o Hoppscotch/Postman:
- Método: POST
- URL: http://localhost:8080/reset-password
- Cabeçalho: Content-Type: application/json
- Corpo da requisição:
{
"email": "email@exemplo.com"
}
4. Enviar a requisição: Clique em Mandar ou Send.
5. Verificar a resposta:
- Se o email existir no banco de dados, a resposta deve ser …
=> Create reset password endpoint

web/package-lock.json, web/package.json, web/src/app/login/components/login-form.tsx, web/src/app/login/page.tsx, web/src/app/page.tsx
Ao armazenar um token na `localStorage` esse token somente fica acessível no browser. Portanto, todo e qualquer componente que queira fazer uso desse token deve ser um client component (componente que roda do browser do cliente/usuário).
Esse pull request vai transferir o token para o `cookie` assim ele fica disponível em server components também. Isso vai, inclusive, facilitar o tratamento de proteção de rotas, que é quando a gente decide se mostra uma tela ou redireciona o usuário caso o token a depender do estado do cookie da sessão.
A operação de salvamento do token foi movido da `localStorage` pro `cookie` usando uma biblioteca de cookie do próprio next. Seu funcionamento é muito similar ao que o `localStorage` faz. Tem o benefício de colocar uma data de expiração do token. Desse …
=> SCRUM-130-adicionar-token-no-cookie-da-sessao

api/src/http/routes/change-password.ts, api/src/repositories/profiles.ts, api/src/validators/change-password.ts
Implementa a funcionalidade que permite aos usuários alterarem suas senhas. Agora, eles podem substituir a senha atual por uma nova e passar por uma confirmação para garantir que a nova senha foi digitada corretamente. Após isso, a nova senha será salva no banco de dados.
- Valida os dados usando changePasswordSchema. Se não retorna uma mensagem de erro.
- Confirma se o usuário está logado (Usando ID decodificado). Se não retorna uma mensagem de erro.
- Compara a senha atual com a senha armazenada no banco de dados. Se não retorna uma mensagem de erro.
- Verificar se a nova senha é diferente da senha atual. Se não retorna uma mensagem de erro.
- Verificar se a nova senha e a senha repetida coincidem. Se não retorna uma mensagem de erro. 
- Feito uma função update no repositório profile. …
=> Implementando a lógica de alterar senha - Backend

api/src/http/routes/change-password.ts, api/src/http/routes/create-profile.ts, api/src/http/routes/get-levels.ts, api/src/http/routes/get-profile.ts, api/src/http/routes/login.ts, api/src/http/routes/reset-password.ts, api/src/http/routes/sudo-login.ts, api/src/http/routes/utils/get-jwt-secret.ts
Este pull request visa centralizar a utilização da chave secreta JWT_SECRET em uma única função. Ao fazer isso, foi adicionado o import desta função em cada arquivo que utiliza a chave secreta, eliminando duplicatas nos arquivos que a utilizavam diretamente.
O código resolve o problema criando um arquivo com a função getJwtSecret para centralizar a chave secreta em um único lugar. Em seguida, o import desta função foi adicionado nos arquivos que precisam da chave secreta, garantindo que a checagem de token esteja configurada corretamente. 
- No terminal, digite **`make run`**
- Acesse o navegador e entre em [localhost:3001/login](url), entre outros, para realizar os testes.
=> Tirando as duplicatas de JWT_SECRET

web/src/app/change-password/components/change-password-form.tsx, web/src/app/components/password-input.tsx, web/src/app/first-login/components/first-login-reset-password.tsx, web/src/app/login/components/login-form.tsx, web/src/app/reset-password/[token]/components/create-new-password-form.tsx
Cria um componente que contém apenas um input de senha.
O código implementa um campo de entrada de senha com uma funcionalidade para mostrar ou ocultar a senha. Ele utiliza um estado (showPassword) para alternar entre os tipos de entrada "password" e "text". Um botão ao lado do campo permite ao usuário alternar a visibilidade da senha, exibindo um ícone correspondente ao estado atual (olho aberto ou fechado). Isso facilita a visualização da senha inserida, garantindo que o usuário possa verificar se digitou a senha corretamente.
Rodar a aplicação com `make run`
Acessar as rotas `login` `change password` `first login` `reset password`
=> Create password input component

api/requests/profiles/change-password.http
Este pull request resolve a falta de um arquivo de http para completar de todas as rotas do projeto. Com isso, todos arquivos para realizar teste no REST CLIENTE.
Na pasta `api/requests` foi criado um novo arquivo chamado `change-password.http`, pois era o único que estava faltando para completar todas as rotas.
- No terminal, digite: `make run`.
- Entre na pasta `api/requests` para realizar testes em todas https existentes.
=> Add arquivos http todas rotas

web/package-lock.json, web/package.json, web/src/app/components/profile-card.tsx, web/src/app/profiles-list/page.tsx, web/src/components/ui/accordion.tsx, web/src/components/ui/avatar.tsx, web/src/components/ui/card.tsx
Cria a tela que lista os perfis de cada company.
Neste PR está sendo implementado o frontend desta nova tela, toda a parte de backend será implementada futuramente.
A tela conta com uma barra de pesquisa que futuramente será usada para buscar perfis, um card de perfil para demonstrar como os perfis serão exibidos e também existe um botão de novo perfil que direciona para a tela de criação de perfil, este botão já está funcionando.
Rodar a aplicação com `make run`
Acessar http://localhost:3001/profiles-list
Estado atual da tela:
=> Create profiles list screen

web/src/app/page.tsx
=> Fix session error on homepage

api/src/http/routes/change-password.ts, api/src/http/routes/get-categories.ts, api/src/http/routes/get-levels.ts, api/src/http/routes/get-profile.ts, api/src/http/routes/login.ts, api/src/http/routes/reset-password.ts, api/src/validators/change-password.ts, api/src/validators/login-form.ts, api/src/validators/profile.ts, api/src/validators/reset-password.ts, api/src/validators/sudo-login.ts, web/src/app/change-password/components/change-password-form.tsx, web/src/app/first-login/components/first-login-reset-password.tsx, web/src/app/login/components/login-form.tsx, web/src/app/new-category/component/new-category-form.tsx, web/src/app/new-company/components/new-company-form.tsx, web/src/app/new-profile/components/new-profile-form.tsx, web/src/app/new-resource/components/new-resource-form.tsx, web/src/app/reset-password/components/send-email-form.tsx
Este pull request padroniza as mensagens de erro, além de ajustar a pontuação, incluindo a implementação do ponto final. No entanto, as mensagens não eram padronizadas.
Os arquivos que continham mensagens de erro estavam fora de contexto e sem pontuação, apesar de serem mensagem semelhante entre si. A solução foi padronizar todas as mensagens e implementar o ponto final, já que a maioria estava sem.
- Fazer o **pull** no VS code para obter as mensagens padronizadas e com a pontuação corrigida.
=> Padronizando mensagens

api/index.ts, web/src/app/page.tsx, web/src/app/profiles-list/page.tsx
Este pull request resolve o problema da tela que exibia uma saudação com um nome fixo, ou seja, o nome do usuário não era alterado corretamente. A função `getHello` foi removida dos arquivos que a utilizavam. 
Com a remoção da função `getHello`, a tela que exibe a saudação agora apresenta **"Olá, Usuário"** . No próximo ticket, será implementada a lógica correta para mostrar o nome do usuário logado.
- Testar os endereços que utilizam a saudação: [localhost:3001](url) e [localhost:3001/profiles-list](url) 
Prints dos testes realizados:
Tela de recurso
Tela de lista de perfis
=> Removed getHello

api/src/http/routes/change-password.ts, api/src/http/routes/create-categories.ts, api/src/http/routes/create-company.ts, api/src/http/routes/create-profile.ts, api/src/http/routes/create-resources.ts, api/src/http/routes/get-levels.ts, api/src/http/routes/login.ts, api/src/http/routes/profile-activate.ts, api/src/http/routes/profile-deactivate.ts, api/src/http/routes/profiles-list.ts, api/src/http/routes/reset-password.ts, api/src/http/routes/sudo-login.ts, api/src/http/routes/utils/http-codes.ts, api/src/http/routes/utils/toggle-profile.ts
Ele melhora a legibilidade e manutenção dos códigos HTTP usados no backend.
Eu criei um arquivo que mapeia os códigos HTTP para nomes descritivos e exportei esse objeto. Agora, em vez de usar números diretamente, podemos importar esse arquivo e utilizar nomes como HttpCodes.SUCCESS para 200, tornando o código mais fácil de entender e manter.
Basta acessar os arquivos que foram alterados e fazer as requests
=> Create httpcodes file

api/src/http/routes/change-password.ts
Adiciona um middleware que apenas possui um console.log
Não está resolvendo nenhum problema, é somente o exemplo de um middleware.
Rodar a aplicação e fazer uma requisição no endpoint `/change-password`
No terminal deve aparecer a mensagem do console.log
Vídeo que assisti
https://www.youtube.com/watch?v=paEDQksNJfg
=> Adding first midleware

api/src/http/middlewares/types/request.ts, api/src/http/middlewares/verify-token.ts, api/src/http/routes/get-categories.ts, api/src/http/routes/login.ts, api/src/http/routes/utils/get-jwt-secret.ts
=> Adiciona middleware de verificação do token ao get companies

api/src/http/middlewares/find-logged-user.ts, api/src/http/middlewares/types/request.ts, api/src/http/middlewares/verify-token.ts, api/src/http/routes/get-categories.ts, api/src/repositories/profiles.ts
=> Adicionando middleware que busca pelo usuário logado

api/src/http/middlewares/refresh-token.ts, api/src/http/middlewares/types/request.ts, api/src/http/routes/get-categories.ts
=> Add refresh token no middleware

api/src/http/middlewares/admin-route.ts, api/src/http/middlewares/sudo-route.ts, api/src/http/routes/get-categories.ts
=> adicionei middleware de sudo e admin

api/src/http/routes/create-categories.ts, api/src/http/routes/create-company.ts, api/src/http/routes/create-resources.ts, api/src/http/routes/get-categories.ts
Melhora o tratamento de erros de validação, garantindo mensagens claras e específicas quando os dados enviados estão inválidos.
Adiciona blocos `try-catch` nos pontos de validação e retorna mensagens detalhadas ao usuário em caso de erro.
Basta acessar algum arquivo http e enviar dados inválidos na requisição.
Exemplo:
Enviei uma requisição sem o campo `name`
=> Add try-catch blocks around parses

api/src/http/controllers/auth.ts, web/src/app/actions.ts, web/src/app/profile/list/components/profile-card.tsx, web/src/app/profile/list/page.tsx, web/src/app/profile/new/components/new-profile-form.tsx, web/src/app/profile/new/page.tsx, web/src/types/profiles.ts
Esse pull request habilita o login como sudo no front end. O backend já estava implementado há algum tempo.
Garante que apenas usuários sudo verão um botão que permitirá fazer o login na aplicação.
- Acesse o endpoint `/profile/list` com um usuário sudo
- Expanda as opções do usuário 
- Clique no botão `fazer login como esse usuário`
=> Scrum 194 sudo login no frontend

web/src/app/components/salute.tsx, web/src/app/page.tsx, web/src/app/profile/list/page.tsx, web/src/app/resource/list/components/empty-resources-list.tsx, web/src/app/resource/list/page.tsx
Para de mostrar `olá, Usuário` pra todo mundo e usa os dados do cookie pro greeting.
Usa dados do cookie de autenticação no salute
Loga e acessa alguma das rotas em que o salute aparece. Exemplo: `/resource/list`.
=> Corrige o greeting do salute

api/src/repositories/profiles.ts
PR bem simples, vou até cortar a descrição.
=> Adiciona updated at à única chamada que estava faltando

api/prisma/migrations/20250327002325_create_appointment_model/migration.sql, api/prisma/migrations/20250327181038_change_appointment_model_first_letter_to_uppercase/migration.sql, api/prisma/migrations/20250330154820_changing_the_date_field_for_the_startsat_and_endsat_fields/migration.sql, api/prisma/schema.prisma
Cria um modelo no banco de dados para guardar informações dos agendamentos.
Criei o modelo Appointment  no arquivo `schema.prisma` com as colunas `id`, `name`, `date`, `description`, `createdAt `e `updatedAt`. Depois rodei os comandos `npx prisma generate` e `npx prisma migrate dev`
Basta rodar a aplicação e acessar o prisma studio para visualizar a tabela.
http://localhost:5555/
=> Scrum 208 criar modelo do banco de dados para agendamentos

api/prisma/seeds/seed-appointments.ts, api/prisma/seeds/seed.ts
Cria um arquivo seed para adicionar dados falsos no modelo de agendamentos.
O arquivo usa a mesma estrutura dos arquivos que o @goislimat já tinha criado para os outros modelos e usa a biblioteca `faker `para gerar dados falsos.
Rodar a aplicação e acessar o prisma studio para visualizar o modelo http://localhost:5555/
=> Add seed for appointments

api/index.ts, api/src/http/controllers/appointment.ts, api/src/http/routes/appointments/index.ts, api/src/repositories/appointments.ts, api/src/services/appointments.ts, api/src/validators/appointments.ts
Cria o endpoint(rota) de appointments.
Utiliza controller e service para montar a estrutura.
1. Usando uma ferramenta de teste de APIs (postman, hoppscothc...)
2. Crie uma requisição do tipo `GET`
3. Coloque o sguinte endereço: `localhost:8080/appointments/1`
4. Se a respota for `"appointment": "From repository id: 1"`, significa que o teste foi realizado com sucesso.
=> Cria o endpoint appointments
